<?php

/**
 * @file
 * Main module file for MBL History DSpaced module.
 */

/**
 * Implements hook_views_api().
 */
function mblhistory_dspaced_views_api() {
  return array("version" => "3.0");
}

/**
 * Implements hook_dspaced_entities_default().
 */
function mblhistory_dspaced_dspaced_entities_default() {
  $entities = array();
  $entities['bundles'] = array(
    'taxonomy_term' => array(
      'dc_subject_mblhistory' => array(
        'name' => t("DC Subject MBL History"),
        'description' => t("MBL History qualifier of the Dublin Core subject property " .
          "Contains keywords that describe the topic of a resource in the context " .
          "of the MBL History community."),
        'machine_name' => 'dc_subject_mblhistory',
      ),
      'dc_type_mblhistory' => array(
        'name' => t("DC Type MBL History"),
        'description' => t("MBL History qualifier of the Dublin Core type property " .
          "Contains keywords that describe the type of a resource in the context " .
          "of the MBL History community."),
        'machine_name' => 'dc_type_mblhistory',
      ),
    ),
  );

  $entities['fields'] = _mblhistory_dspaced_fields();
  $entities['instances'] = array(
    'node' => array(
      'dspaced_entities_item' => $entities['fields'],
    ),
  );

  return $entities;
}

/**
 * Implements hook_dspaced_item_feeds_importer_fields_alter().
 */
function mblhistory_dspaced_dspaced_item_feeds_importer_fields_alter(&$fields) {
  $fields = array_merge($fields, _mblhistory_dspaced_fields());
}

/**
 * Helper function to define custom DSpace Item fields.
 */
function _mblhistory_dspaced_fields() {
  return array(
    'dc_subject_mblhistory' => array(
      'field_name' => 'dc_subject_mblhistory',
      'label' => t('DC Subject MBL History'),
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'type' => 'taxonomy_term_reference',
      'settings' => array(
        'allowed_values' => array(
          array(
            'vocabulary' => 'dc_subject_mblhistory',
            'parent' => 0,
          ),
        ),
      ),
      'xpath' => "metadata/metadataentity[schema = 'dc' and " .
                 "element = 'subject' and qualifier = 'mblhistory']/value",
    ),
    'dc_type_mblhistory' => array(
      'field_name' => 'dc_type_mblhistory',
      'label' => t('DC Type MBL History'),
      'cardinality' => 1,
      'type' => 'taxonomy_term_reference',
      'settings' => array(
        'allowed_values' => array(
          array(
            'vocabulary' => 'dc_type_mblhistory',
            'parent' => 0,
          ),
        ),
      ),
      'xpath' => "metadata/metadataentity[schema = 'dc' and " .
                 "element = 'type' and qualifier = 'mblhistory']/value",
    ),
  );
}
